<?php
/**
 * Created by PhpStorm.
 * User: wlb-71
 * Date: 2017/12/25
 * Time: 11:38
 */

namespace app\api\controller;


class Wxpay extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        vendor('WeiXinpay.wxpay');
    }

    /**
     * @return \think\response\Json
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * 微信支付 接口
     */
    public function wxpay()
    {
        $pay_sn = input('order_sn');
        if (empty($pay_sn)){
            return json(array('status'=>0,'err'=>'支付信息错误！'));
        }

        $orderInfo = db('order')->where('order_sn='.$pay_sn)->find();
        if (empty($orderInfo)){
            return json(array('status'=>0,'err'=>'没有找到支付订单！'));
        }
        if ($orderInfo['status'] !== 10){
            return json(array('status'=>0,'err'=>'订单状态异常！'));
        }

        $openId = db('user')->where('id='.$orderInfo['uid'])->value('openid');
        if (empty($openId)){
            return json(array('status'=>0,'err'=>'用户状态异常！'));
        }

        $input = new \WxPayUnifiedOrder();
        $input->SetBody("wzx商城商品购买_".trim($orderInfo['order_sn']));
        $input->SetAttach("wzx商城商品购买_".trim($orderInfo['order_sn']));
        $input->SetOut_trade_no($pay_sn);
        $input->SetTotal_fee(floatval($orderInfo['amount'])*100);
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 3600));
        $input->SetGoods_tag("wzx商城商品购买_".trim($orderInfo['order_sn']));
        $input->SetNotify_url('https://xxx.xxxx.com/index.php/Api/Wxpay/notify');
        $input->SetTrade_type("JSAPI");
        $input->SetOpenid($openId);
        $order = \WxPayApi::unifiedOrder($input);
        $arr = [
            'appId'     => $order['appid'],
            'nonceStr'  => $order['nonce_str'],
            'package'   => 'prepay_id=' . $order['prepay_id'],
            'signType'  => 'MD5',
            'timeStamp' => time()
        ];
        $str = $this->ToUrlParams($arr);
        $jmstr = $str.'&key='.\WxPayConfig::KEY;
        $arr['paySign'] = strtoupper(MD5($jmstr));
        return json(array('status'=>1,'arr'=>$arr));
    }

    public function notify()
    {
        $res_xml = file_get_contents("php://input");
        libxml_disable_entity_loader(true);
        $ret = json_decode(json_encode(simplexml_load_string($res_xml,'simpleXMLElement',LIBXML_NOCDATA)),true);

        $path = "./Data/log/";
        if (!is_dir($path)){
            mkdir($path,0777);  // 创建文件夹test,并给777的权限（所有权限）
        }
        $content = date("Y-m-d H:i:s").'=>'.json_encode($ret);  // 写入的内容
        $file = $path."weixin_".date("Ymd").".log";    // 写入的文件
        file_put_contents($file,$content,FILE_APPEND);  // 最简单的快速的以追加的方式写入写入方法，

        $data = array();
        $data['order_sn'] = $ret['out_trade_no'];
        $data['pay_type'] = 'weixin';
        $data['trade_no'] = $ret['transaction_id'];
        $data['total_fee'] = $ret['total_fee'];
        $result = $this->orderhandle($data);
        if (is_array($result)) {
            $xml = "<xml><return_code><![CDATA[SUCCESS]]></return_code><return_msg><![CDATA[OK]]></return_msg>";
            $xml.="</xml>";
            echo $xml;
        }else{
            $contents = 'error => '.json_encode($result);  // 写入的内容
            $files = $path."error_".date("Ymd").".log";    // 写入的文件
            file_put_contents($files,$contents,FILE_APPEND);  // 最简单的快速的以追加的方式写入写入方法，
            echo 'fail';
        }
    }

    /**
     * @param $data
     * @return array|string
     * @throws \think\Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @throws \think\exception\PDOException
     * 订单处理接口
     */
    public function orderhandle($data)
    {
        $order_sn = trim($data['order_sn']);
        $pay_type = trim($data['pay_type']);
        $trade_no = trim($data['trade_no']);
        $total_fee = floatval($data['total_fee']);
        $check_info = db('order')->where('order_sn="'.$order_sn.'"')->find();
        if (!$check_info) {
            return "订单信息错误...";
        }

        if ($check_info['status']<10 || $check_info['back']>'0') {
            return "订单异常...";
        }

        if ($check_info['status']>10) {
            return array('status'=>1,'data'=>$data);
        }

        $up = array();
        $up['type'] = $pay_type;
        $up['price_h'] = sprintf("%.2f", floatval($total_fee / 100));
        $up['status'] = 20;
        $up['trade_no'] = $trade_no;
        $res = db('order')->where('order_sn="'.$order_sn.'"')->update($up);
        if ($res) {
            //处理优惠券
            if (intval($check_info['vid'])) {
                $vou_info = db('user_voucher')->where('uid='.intval($check_info['uid']).' AND vid='.intval($check_info['vid']))->find();
                if (intval($vou_info['status'])==1) {
                    db('user_voucher')->where('id='.intval($vou_info['id']))->update(array('status'=>2));
                }
            }
            return array('status'=>1,'data'=>$data);
        }else{
            return '订单处理失败...';
        }
    }

    /**
     * @param $urlObj
     * @return string
     * 构建字符串
     */
    private function ToUrlParams($urlObj)
    {
        $buff = "";
        foreach ($urlObj as $k => $v)
        {
            if($k != "sign"){
                $buff .= $k . "=" . $v . "&";
            }
        }

        $buff = trim($buff, "&");
        return $buff;
    }
}